Repository openshift/community, pull requests merged in 2019-09, with the labels that each got.

#1 Add initial WG members
  MEMBERS.md
Labels: size/S

#2 Add OWNERS file
  OWNERS
Labels: approved, lgtm, size/S

#15 Add Vadim Rutkovsky
  MEMBERS.md
Labels: approved, lgtm, size/XS

#10 Update readme.md get involved links
  README.md
Labels: approved, lgtm, size/XS

#35 Add Chairs to reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#36 Add Steve to reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#40 Add new Members
  MEMBERS.md
Labels: approved, lgtm, size/S

#3 Call for Agreement: OKD WG Charter (Revised Proposal)
  CHARTER.md
Labels: approved, lgtm, size/L

#43 Add Jaime Magiera (@JaimeMagiera) to MEMBERS.md
  MEMBERS.md
Labels: approved, lgtm, size/XS

#46 Add Jay Ryan as a member
  MEMBERS.md
Labels: approved, lgtm, size/XS

#44 Minor Charter Corrections
  CHARTER.md
Labels: approved, lgtm, size/M
